name: hotels_picker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2024.01.24.01

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  # flutter_bloc: ^8.1.3
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_libphonenumber: ^2.2.1
  email_validator: ^2.1.17
  calendar_date_picker2: ^0.5.3
  country_picker: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  retrofit_generator: ^7.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/amenities.svg
    - assets/images/included.svg
    - assets/images/excluded.svg
    - assets/images/arrow_forward.svg
    - assets/images/arrow_back.svg
    - assets/images/arrow_up.svg
    - assets/images/arrow_down.svg
    - assets/images/plus.svg
    - assets/images/party.svg
